In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.utils import shuffle as shuffler
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import model_selection

In [ ]:
import io
from google.colab import files
uploaded = files.upload()
data = pd.read_excel(io.BytesIO(uploaded['azeri_news.xlsx']))

In [2]:
arts = pd.read_excel('azeri_news (1).xlsx', sep = '\t', names = ['Categories', 'Titles', 'Articles'])

In [3]:
arts

Categories  ...                                           Articles
0           Maraqlı  ...  Naviforce Sport Saat 2016 Yapon Mexanizmi Yapo...
1           Maraqlı  ...  ŞOK ! ŞOK ! ŞOK ! Xanımlar və bəylər , bel və ...
2           Maraqlı  ...  Dəyərindən qat-qat Aşağı Qiymətə. Həzi Aslanov...
3             İdman  ...   2028-ci il Yay Olimpiya və Paralimpiya Oyunla...
4             Dünya  ...   Türkiyədə daha bir zəlzələ meydana gəlib.   L...
...             ...  ...                                                ...
49995       Siyasət  ...    AXCP sədri "Milli Şura"nın mitinqində qəsdən...
49996       Siyasət  ...    "Ümumiyyətlə, Milli Şuraya xoş olan, hətta o...
49997         Dünya  ...    Türkiyənin İstanbul şəhərinin Ataşehir rayon...
49998         Dünya  ...    Rusiyanı tərk edərək İŞİD sıralarında döyüşə...
49999  İqtisadiyyat  ...   Ukrayna Mərkəzi Bankı (NBU) bu gün keçirdiyi ...

[50000 rows x 3 columns]

In [4]:
sh = shuffler(arts)

In [5]:
sh

Categories  ...                                           Articles
27058     Maraqlı  ...   Amerika-Çin şirkəti Lucid Motors 1000-güclü e...
32034     Siyasət  ...  Türkiyə prezidenti Rəcəb Tayyib Ərdoğan və onu...
11403     Maraqlı  ...  Oğuz Meşə Mühafizəsi və Bərpası Müəssisəsinin ...
11126       Dünya  ...   Rusiyanın ABŞ-dakı diplomatik nümayəndəliklər...
49709       Dünya  ...    Finlandiyada sərnişin qatarı zirehli transpo...
...           ...  ...                                                ...
21611     Maraqlı  ...    Avstraliya ərazisində Yerə təqribən 4,5 mily...
14443     Siyasət  ...   Azərbaycan Rusiya və ABŞ-ın münaqişəni həll e...
12367       Dünya  ...   Mumbaydan gələn və İranla Azərbaycan ərazisi ...
18837     Siyasət  ...   Bakı. Ənvər Məmmədov, Rufiz Hafizoğlu - Trend...
3351   Mədəniyyət  ...   Mədəniyyət və turizm nazirinin müavini Nazim ...

[50000 rows x 3 columns]

In [6]:
sh_d1=sh["Articles"]
sh_d2=sh["Categories"]

In [7]:
ts1, tr1, ts2, tr2 = model_selection.train_test_split(sh_d1, sh_d2, test_size=0.2, random_state=4)

In [8]:
vectorizer = CountVectorizer()

In [9]:
tr1_t = vectorizer.fit_transform(tr1)
print( tr1_t )

  (0, 15016)	7
  (0, 33873)	1
  (0, 38325)	1
  (0, 103309)	1
  (0, 102435)	1
  (0, 39850)	1
  (0, 33966)	1
  (0, 34128)	1
  (0, 79062)	1
  (0, 68595)	1
  (0, 105245)	5
  (0, 55238)	1
  (0, 84754)	2
  (0, 39522)	3
  (0, 25047)	1
  (0, 84422)	1
  (0, 100336)	1
  (0, 92754)	7
  (0, 12145)	1
  (0, 79060)	3
  (0, 77726)	1
  (0, 100854)	1
  (0, 102208)	1
  (0, 25198)	1
  (0, 91125)	3
  :	:
  (9999, 104492)	2
  (9999, 84908)	1
  (9999, 108222)	1
  (9999, 50102)	1
  (9999, 69736)	1
  (9999, 59370)	1
  (9999, 104491)	1
  (9999, 108223)	1
  (9999, 18421)	1
  (9999, 67030)	1
  (9999, 6109)	1
  (9999, 14977)	1
  (9999, 18419)	1
  (9999, 51860)	1
  (9999, 44236)	1
  (9999, 946)	1
  (9999, 16516)	1
  (9999, 50105)	1
  (9999, 74684)	1
  (9999, 56696)	1
  (9999, 43418)	1
  (9999, 80962)	1
  (9999, 41483)	1
  (9999, 72714)	1
  (9999, 8132)	1


In [10]:
print( vectorizer.vocabulary_ )

Output hidden; open in https://colab.research.google.com to view.

In [11]:
tr2 = tr2.astype('str')

In [25]:
mlpClass = MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter = 200)
svcClass = SVC(kernel = 'linear', gamma = 'auto', C = 0.5)
dstClass = DecisionTreeClassifier(criterion="entropy")

In [26]:
 mlpClass.fit(tr1_t, tr2)
 svcClass.fit(tr1_t, tr2)
 dstClass.fit(tr1_t, tr2)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [32]:
def Av_P_R(val2, predAlgo):
  from sklearn.metrics import recall_score
  from sklearn.metrics import confusion_matrix
  print('Classification Report: \n', classification_report(val2, predAlgo)),
  print('Confusion Matrix: \n', confusion_matrix(val2, predAlgo)), 
  print('Recall Score: \n', recall_score(val2, predAlgo, average='micro'))

In [33]:
def SVML_Algo(val1,val2,algo):
  predAlgo = algo.predict(val1)
  return Av_P_R(val2, predAlgo)

In [29]:
crv_t = vectorizer.transform(ts1)

In [34]:
print(SVML_Algo(crv_t, ts2, mlpClass))

Classification Report: 
               precision    recall  f1-score   support

       Dünya       0.73      0.79      0.76     10829
     Maraqlı       0.75      0.73      0.74     12625
  Mədəniyyət       0.80      0.51      0.62      1242
     Siyasət       0.84      0.71      0.77      5231
       İdman       0.89      0.91      0.90      4990
İqtisadiyyat       0.77      0.86      0.81      5083

    accuracy                           0.77     40000
   macro avg       0.79      0.75      0.77     40000
weighted avg       0.78      0.77      0.77     40000

Confusion Matrix: 
 [[8516 1625   19  241  148  280]
 [2244 9169  100  276  336  500]
 [  89  379  637   41    8   88]
 [ 559  463   39 3708   32  430]
 [ 162  232    0   36 4539   21]
 [ 123  421    5  138   15 4381]]
Recall Score: 
 0.77375
None


In [35]:
print(SVML_Algo(crv_t, ts2, svcClass))

Classification Report: 
               precision    recall  f1-score   support

       Dünya       0.73      0.78      0.76     10829
     Maraqlı       0.73      0.74      0.74     12625
  Mədəniyyət       0.70      0.59      0.64      1242
     Siyasət       0.80      0.77      0.79      5231
       İdman       0.90      0.87      0.88      4990
İqtisadiyyat       0.83      0.77      0.80      5083

    accuracy                           0.77     40000
   macro avg       0.78      0.75      0.77     40000
weighted avg       0.77      0.77      0.77     40000

Confusion Matrix: 
 [[8478 1812   30  249  120  140]
 [2029 9401  203  329  301  362]
 [  92  290  736   79    6   39]
 [ 467  452   54 4027   16  215]
 [ 218  364    8   61 4322   17]
 [ 262  602   19  282   18 3900]]
Recall Score: 
 0.7716
None


In [36]:
print(SVML_Algo(crv_t, ts2, dstClass))

Classification Report: 
               precision    recall  f1-score   support

       Dünya       0.69      0.72      0.70     10829
     Maraqlı       0.71      0.70      0.70     12625
  Mədəniyyət       0.41      0.32      0.36      1242
     Siyasət       0.68      0.68      0.68      5231
       İdman       0.81      0.74      0.77      4990
İqtisadiyyat       0.66      0.68      0.67      5083

    accuracy                           0.69     40000
   macro avg       0.66      0.64      0.65     40000
weighted avg       0.69      0.69      0.69     40000

Confusion Matrix: 
 [[7799 1916  100  346  270  398]
 [1988 8868  228  533  431  577]
 [ 166  315  399  201   35  126]
 [ 454  518  102 3559   72  526]
 [ 444  450   42  174 3712  168]
 [ 507  489  104  453   81 3449]]
Recall Score: 
 0.69465
None
